apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: scv
data:
  SERVER_PORT: "8888"
  AUTH_PORT: "8889"
  API_PORT: "8790"
  GRAFANA_PORT: "3000"
  # CORS Configuration
  CLIENT_URL: "https://4.217.221.100"
  CLIENT_PORT: "8080"
  CORS_ALLOWED_ORIGINS: "http://4.217.221.100,https://4.217.221.100"
  #  MANAGEMENT_ENDPOINTS_GATEWAY_ENABLED: "true"
  MANAGEMENT_ENDPOINTS: "health,info,prometheus,gateway,loggers,health,info,env"
  LOG_PATH: ""
  #SERVER_BASE_URL: "20.249.129.83"
  SERVER_BASE_URL: "http://0.0.0.0"
#  SPRING_PROFILES_ACTIVE: "prod"
#  SPRING_CLOUD_GATEWAY_ROUTES_0_URI: "http://apim-auth:8889"
# 파일 로깅 OFF + 콘솔(JSON)
# LOGGING_FILE_NAME: ""
# LOGGING_FILE_PATH: ""
# LOGGING_PATTERN_CONSOLE: >-
#   {"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%level","service":"apim-gateway",
#    "pod":"${POD_NAME:-}","node":"${NODE_NAME:-}","thread":"%thread","logger":"%logger{36}",
#    "message":"%msg"}%n
