apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: scv
  annotations:
    kubernetes.io/ingress.class: nginx
    # 프록시 버퍼 튜닝
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    # 클라이언트 헤더 버퍼 튜닝
    nginx.ingress.kubernetes.io/client-header-buffer-size: "64k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "4 128k"
    # Host 매칭이 없어도 이 인증서를 기본으로 제공
    #nginx.ingress.kubernetes.io/default-ssl-certificate: scv/scv-web-ip-tls
    # http -> https 리다이렉트
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - secretName: scv-web-ip-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-nginx-service
                port:
                  number: 80
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: apim-gateway
                port:
                  number: 8888
