# ConfigMap - 일반 설정 정보
apiVersion: v1
kind: ConfigMap
metadata:
  name: cc-backend-config
  namespace: scv
data:
  SERVER_PORT: "2790"
  SERVER_BASE_URL: "http://0.0.0.0"
  SERVER_CONTEXT_PATH: "/stml"
  DB_HOST: "pg-flex-scv01.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "rnd"
  DB_SCHEMA: "scvad"
  REPO_DB_SCHEMA: "scvdb"
  DB_USERNAME: "rnduser"
  REDIS_SERVER_HOST: "redis-service.scv.svc.cluster.local"
  REDIS_SERVER_PORT: "6379"
  REPO_DB_NAME: "rnd"
  LOGGING_PATH: "./logs"
  SCV_COMMMANDER_HOST: "http://scv-engine"
  SCV_SERVER_PORT: "8877"
  SCV_END_POINT: "scv/api/command/invoice"
  SCV_CC_SERVER_PORT: "1790"
  ALLOWED: "http://localhost:8080,https://localhost:8080,http://localhost:3000,http://4.230.159.239,https://4.230.159.239"
  UPLOAD_DIR: "/app/images"
  AES_KEY: "G4vJzKpS2oLtQwRm"
  AES_IV: "M9yHcA3xB8uFjE5L"
  MANAGEMENT_ENDPOINTS: "health,info,prometheus"
  DB_MAXIMUM_POOL_SIZE: "1"
  REPO_MAXIMUM_POOL_SIZE: "1"
---
# Secret - 보안이 필요한 정보
apiVersion: v1
kind: Secret
metadata:
  name: cc-backend-secret
  namespace: scv
type: Opaque
stringData:
  DB_PASSWORD: Rnd@user!
