# ConfigMap - 일반 설정 정보
apiVersion: v1
kind: ConfigMap
metadata:
  name: apim-auth-config
  namespace: scv
data:
  SERVER_PORT: "8889"
  SERVER_BASE_URL: "http://0.0.0.0"
  DB_HOST: "pg-flex-scv01.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "rnd"
  DB_SCHEMA: "scvad"
  DB_USERNAME: "rnduser"
  MANAGEMENT_ENDPOINTS: "health,info,metrics,prometheus"
  SPRING_PROFILES_ACTIVE: "prod"
---
# Secret - 보안이 필요한 정보
apiVersion: v1
kind: Secret
metadata:
  name: apim-auth-secret
  namespace: scv
  labels:
    app: apim-auth
type: Opaque
stringData:
  #DB_PASSWORD: UndkQHVzZXIh
  DB_PASSWORD: Rnd@user!
  JWT_SECRET_KEY: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJlLWNoYW5nZS1pbi1wcm9kdWN0aW9u
